### PR TITLE
Prohibit more than 42 layers in the core

### PR DESCRIPTION
**Pull request by crosbymichael**
We need to do this because we still support aufs
and users on other drivers can push incompat images
to the registory that aufs users cannot use.

### CODE REVIEW

**Comment by jpetazzo** [comment]
Hey, out of curiosity, what's the detailed rationale behind this?
People have been asking how to bypass the 42 layers limit, and we've always told them "wait for device mapper!" so... what should we tell them now?

**Comment by creack** [comment]
LGTM

**Comment by creack** [comment]
@jpetazzo We can't allow more than 42 layers just yet. Devicemapper indeed supports it, but then, if you push a 50 layer image to the registry, most people won't be able to use it. We'll enable this once we support more than 42 layers for AUFS.

**Comment by tianon** [comment]
So the official answer would be that a workaround for AUFS is forthcoming, which will then allow the restriction to be lifted for DM.

Right?

**Comment by vieux** [comment]
right

On Tue, Nov 19, 2013 at 4:25 PM, Tianon Gravi notifications@github.comwrote:

> So the official answer would be that a workaround for AUFS is forthcoming,
> which will then allow the restriction to be lifted for DM.
> 
> Right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shykes/docker/pull/50#issuecomment-28853175
> .

## 

Victor VIEUX
http://vvieux.com

**Comment by jpetazzo** [comment]
Erf :-(

**Comment by alexlarsson** [comment]
Why not just fix the aufs backend?
The simplest fix is to just hardlink-copy a new base layer when we reach 42 layers.

**Comment by shykes** [comment]
Those are not mutually exclusive. Limitimg dm to 42 layers is an easy
short-term fix until aufs + hardlinks is implemented, tested etc.

**Comment by jpetazzo** [comment]
Hey, I would be extremely careful with AUFS+hardlinks.
If you have details about how you plan to use hardlinks, I'd love to read
about it.

On Wed, Nov 20, 2013 at 1:43 AM, Solomon Hykes notifications@github.comwrote:

> Those are not mutually exclusive. Limitimg dm to 42 layers is an easy
> short-term fix until aufs + hardlinks is implemented, tested etc.
> 
> On Wednesday, November 20, 2013, alexlarsson wrote:
> 
> > Why not just fix the aufs backend?
> > The simplest fix is to just hardlink-copy a new base layer when we reach
> > 42 layers.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/shykes/docker/pull/50#issuecomment-28871791>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shykes/docker/pull/50#issuecomment-28874367
> .

## 

@jpetazzo https://twitter.com/jpetazzo
Latest blog post: http://jpetazzo.github.io/2013/11/17/flynn-docker-paas/

**Comment by alexlarsson** [comment]
Here is a fix for the 42 layer limit https://github.com/shykes/docker/pull/66

**Pull request merged**
