### PR TITLE
Add flag to set default graph driver

### PR DESCRIPTION
**Pull request by crosbymichael**
Add a cli flag to select a graph driver

### CODE REVIEW

**Comment by vieux** [comment]
How can we choose the driver we want to use in the tests ?

**Comment by crosbymichael** [comment]
@vieux `graphdriver.DefaultDriver = "dummy"`

**Comment by vieux** [comment]
yes, but if I want to run the test using aufs, can I do it without editing the code ?

**Comment by crosbymichael** [comment]
No, we will have to edit `make.sh` to support that or do something else.

**Comment by vieux** [comment]
What would do `make.sh` ? a `sed` ?

Why not keep the env var if there is no flag

**Comment by crosbymichael** [comment]
@vieux so have both a env var and the flag for the cli ?

**Comment by vieux** [comment]
Why not, check flag, no to present, try env, if not present fall back to dummy, too ugly ?

**Comment by tianon** [comment]
Or fall back on the "autodetection" we've got that uses AUFS where it's available.  Definitely big +1 for having a cli flag, especially since that's so easy to set via `/etc/default/docker` or `/etc/conf.d/docker`, if you want to control your driver choice at daemon runtime.

This brings up a good point - will it be possible for me to compile docker without the AUFS driver, for example?  I have some ideas for how to accomplish this easily, if it's something we'd be interested in having.

**Comment by crosbymichael** [comment]
Ok, I think we will need to keep both a cli flag and env var for the tests.

**Comment by tianon** [comment]
If I specify `-graph-driver=somethingbogus` it will error out somewhere down inside the `GetDriver` code, right?

Also, would it be possible/viable/desirable to make `-graph-driver=list` be a special case that lists all the available drivers?  I think it'd be useful to have some way to do so, and that seems like a reasonable method for doing so to me.

**Comment by creack** [comment]
+1 on list :)

**Comment by crosbymichael** [comment]
@tianon @creack The list is hard coded right now, plus it is a want and not a need.  I don't have time right now to implement it properly.  I think it can wait.

**Comment by crosbymichael** [comment]
ping @vieux

**Comment by vieux** [comment]
LGTM

**Comment by tianon** [comment]
@michaelcrosby sounds good to me :)

**Pull request merged**
