### PR TITLE
Implement CLI for ls, create, rm, join leave

### PR DESCRIPTION
**Pull request by aanand**

### CODE REVIEW

**Comment by aanand** [comment]
ping @shykes and anyone else working on networks - want me to rebase this?

**Comment by shykes** [comment]
Sorry I missed this. @icecrime coukd you take a look today based on our
pairing session?

**Comment by icecrime** [comment]
I'm looking into cherry-picking these commits to add them on top of my latest PR if that's ok with you.

**Comment by shykes** [comment]
@icecrime is everything from this branch covered in the cherry-picks I pushed today? If so, ok to close this?

**Comment by icecrime** [comment]
@shykes Yes, I believe it's all covered.

**Pull request closed without merging**
