### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by codeaholics**

### CODE REVIEW

**Comment by crosbymichael** [comment]
@codeaholics Should it be spelled `dependent` and not `dependant`

**Comment by codeaholics** [comment]
Depends if you're American or English. I'm English. But I'll take your
version. Anything is better than the version with a 'd' at the end ;-)

**Comment by codeaholics** [comment]
http://www.grammar-monster.com/easily_confused/dependant_dependent.htm

**Comment by crosbymichael** [comment]
This change has been merged in master with the correct American spelling ;)

**Pull request closed without merging**
