### PR TITLE
Support capabilities bits in xattrs in layers

### PR DESCRIPTION
**Pull request by alexlarsson**
This adds support for detecting changes in the security.capability xattr, and enables the right flag in the tar commands to store/extract it.

This is needed for docker to work well with fedora packages. For instance, the Fedora httpd package has a /usr/sbin/suexec that has a capabilities bit set instead of being setuid. I verified this patchset by doing:

```
docker run -t -i mattdm/fedora bash
yum install -y httpd attr
bash-4.2# attr -l /usr/sbin/suexec 
Attribute "selinux" has a 32 byte value for /usr/sbin/suexec
Attribute "capability" has a 20 byte value for /usr/sbin/suexec
exit
docker commit ID
docker run -t -i ID bash
bash-4.2# attr -l /usr/sbin/suexec 
Attribute "selinux" has a 32 byte value for /usr/sbin/suexec
Attribute "capability" has a 20 byte value for /usr/sbin/suexec
```

### CODE REVIEW

**Comment by alexlarsson** [comment]
This is a rebase of https://github.com/dotcloud/docker/pull/2163 on request from @crosbymichael

**Comment by crosbymichael** [comment]
On the ubuntu image that we use to test,release,etc I receive the following error with this PR.

`tar: unrecognized option '--xattrs'`

Version:
tar (GNU tar) 1.26

**Comment by alexlarsson** [comment]
Ugh, I have:
$ tar --version
tar (GNU tar) 1.26

Maybe its a build option?

**Comment by tianon** [comment]
Our build comes from apt (directly out of the ubuntu repos).  It seems odd that command line flags would be modified by a compile-time option.  Here on Gentoo I've got `tar (GNU tar) 1.26`, and I've got `--xattrs`.

I tested ubuntu 12.04, 12.10, 13.04, and 13.10, and none of them have `--xattrs`, and they all have `tar (GNU tar) 1.26`.  It looks like 14.04 is going to have 1.27, however: http://packages.ubuntu.com/trusty/tar

**Comment by alexlarsson** [comment]
So, the fedora tar 1.26 has xattrs patched in. The upstream support is only in 1.27.

**Comment by alexlarsson** [comment]
As an update on this, i've slowly been replacing the shelling out to tar with use of archive/tar, and I have code based on that that adds xattrs instead. Will put it here when ready.

**Pull request closed without merging**
