### PR TITLE
Dm plugins archive tests

### PR DESCRIPTION
**Pull request by alexlarsson**
This has two fixes and then adds a bunch of tests for the archives/changes.go code

Unfortunately one test is disabled because it fails (due to bugs) but we want to fix those so we can enable the test.

### CODE REVIEW

**Comment by crosbymichael** [comment]
@alexlarsson 

I get the following errors when trying to build 

```
# github.com/dotcloud/docker
./runtime.go:21: imported and not used: "path/filepath"
./runtime.go:744: missing return at end of function
```

**Comment by alexlarsson** [comment]
sorry about that

**Comment by crosbymichael** [comment]
LGTM

**Comment by creack** [comment]
LGTM

**Pull request merged**
