### PR TITLE
Rename dummy driver to vfs

### PR DESCRIPTION
**Pull request by crosbymichael**

### CODE REVIEW

**Comment by tianon** [comment]
I'm going to just comment with "volume file system" here, for posterity. :)

:+1:

**Comment by vieux** [comment]
@crosbymichael shouldn't change every reference in the code also ?

**Comment by crosbymichael** [comment]
@vieux Updated

**Comment by shykes** [comment]
LGTM

**Comment by creack** [comment]
LGTM

**Pull request merged**
