### PR TITLE
Nets fixes

### PR DESCRIPTION
**Pull request by erikh**
This fixes `nets ls` (and the zero-arg form) and `nets rm`.

NOTE: because of the vxlan issues that I will fix later today (revolving around state and parameter passing), you will have to `ip link del vxdefault` to be able to successfully create and rm networks. The functionality works, the driver just needs to be tweaked a bit to handle peering appropriately.

### CODE REVIEW

**Comment by erikh** [comment]
This builds on #119 and #120 so merge/review those first please.

**Comment by icecrime** [comment]
Besides a parasite `fmt.Println`, LGTM.

I am however wondering if we actually need a two-step operation to `AddNetwork` and `GetNetwork` from the driver rather than having `AddNetwork(string) (Network, err)`.

**Comment by erikh** [comment]
I do that to ensure the state is consistent as it would be restored; I do agree though this should be done a better way. Let’s merge now and I’ll mull it over and put it on my task list.

**Pull request merged**
